### PR TITLE
Integrate the OpenLab CI system to telekom provider repo

### PR DESCRIPTION
**Pull request by liusheng**
This change want to support the OpenLab CI system with opentelekomcloud
provider repo. The CI job will running the acceptance tests of this
provider against a telekom cloud environment.

To trigger this job, please comment "recheck" under a PR.

- The telekom CI job definition: # theopenlab/openlab-zuul-jobs/pull/36
- The PR to test the job: #  liu-sheng/terraform-provider-opentelekomcloud/pull/1

### CODE REVIEW

**Comment by gator1** [comment]
Pull req to master will not be accepted. All has to go to integration
first.

**Comment by liusheng** [comment]
Hi @gator1, Thanks for comments, to integrate with the OpenLab CI, we also need to install the openlab-ci github app,  the installation link: https://github.com/apps/theopenlab-ci

Thanks!

**Comment by liusheng** [comment]
Hi @gator1 I have changed this PR to request to merge to integration branch, and the jobs have been added to openlab CI. please help to review this and help to install the github app. thanks in advance!

**Comment by gator1** [comment]
why does this need to install an app? Does installing app mean the provider would depend on the CI app?

**Comment by liusheng** [comment]
@gator1 the OpenLab need a trigger to trigger Jobs defined in the .zuul.yaml, OpenLab CI will capture some events such as "PR submission" or comment "recheck" under a PR. So we need a github app as the trigger to push the events of this repo to the specified host (the CI events listener). It won't add any dependency of this repo, just a setting option of this repo. 
BTW, please also set the branch which want to be trigger  CI as protected branch, for  this repo, we need to set the integration branch as protected branch (we usually set master branch protected in other repos). That is because if don't set the protected branch, the OpenLab CI will scan every branch of this repo to loading config, if one branch don't have the .zuul.yaml added, the job will cause error and any new branch changes will also effect the CI jobs, if we set the integration branch as protected branch, CI will only care this branch.

For more about the CI integration, please see: https://github.com/theopenlab/cicd-howto#connect-to-openlab

Thanks!

**Comment by gator1** [comment]
I understand that you need this for your CI to work. I question how this affect the provider itself. 
If CI is down, can I run the acceptance test? What is the impact of the app that I have to install for your test to run? If this app crashes what happen to my test?

**Comment by gator1** [comment]
I think that you need to provide me a document explaining how your system works with github and this provider.

**Comment by liusheng** [comment]
Hi Gary,

To be exact, we propose to add a CI job for the terraform-provider-opentelekomcloud, and the CI system have integrated with many other repos: terraform-provider-openstack, gophercloud, terraform-provider-telefonicaopencloud, terraform-provider-flexibleengine. it won't effect the provider it self, the CI will only run the acceptance tests on a dedicated OTC environment of specific events triggered.  the purpose of this CI job is to check the functionalities opentelekomcloud provider working with a real OTC environment, after CI job running, the testing results will be commented under the PRs, there is an example of the telefonica provider[1]. 

If the CI down, it will only comment a failure under the PRs or won't be triggered, you can certainly run the acceptance tests in your own env, but in this case, we will do our best effort to fix the CI at fist time :) for the job definition, may you can also take a look, it mainly includes a ansible script to run the acceptance tests of this repo. see[2]

The github app is not a real app, it is more like a webhook for the CI jobs triggering which only sent the github events(PR submission, PR comments) to a specific CI listener host, so it won't effect anything, and it won't crash :) for more about github app, please see[3]

Sorry for the documentation, about the OpenLab, we don't have a very rich documentation yet, and we will supply in the future. for more details about the OpenLab, you can see[4] [5][6]

Thanks in advance!

[1] https://github.com/huawei-clouds/terraform-provider-telefonicaopencloud/pull/20
[2] https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/terraform-provider-opentelekomcloud-acceptance-test-opentelekomcloud/run.yaml
[3] https://developer.github.com/apps/building-github-apps/creating-a-github-app/
[4] https://openlabtesting.org/
[5] https://github.com/theopenlab
[6] https://github.com/theopenlab/cicd-howto

**Comment by liusheng** [comment]
Hi @gator1 , thanks a lot for merging this, to make the OpenLab CI work with opentelekomcloud provider, we need to install the github app: https://github.com/apps/theopenlab-ci and set the `integration` branch as a protected branch. 

Thanks!

**Pull request merged**
