### PR TITLE
 sync vendor/github.com/gophercloud for the smn

### PR DESCRIPTION
**Pull request by zengchen1024**

### CODE REVIEW

**Comment by gator1** [comment]
Have you run an acceptance test?

**Comment by zengchen1024** [comment]
@gator1 yes, I run the acceptance test. Is there any problem?

**Comment by gator1** [comment]
You need to provide a full acceptance test log, not just your test, the full test before I can take your code in, no exception.

**Comment by zengchen1024** [comment]
Please see the acceptance test log at http://paste.openstack.org/show/638985/

**Comment by zengchen1024** [comment]
@gator1 sorry, the size of log is too big, I send the log to your email of Huawei. The log at http://paste.openstack.org/show/638985/ is not complete.

**Pull request merged**
